### ISSUE TITLE
Feature: Option to change the owner of an plugin

### ISSUE THREAD

**Issue by BlockyTheDev** [HangarMC/Hangar#711] opened 2022-06-19 22:27 UTC
As far as I saw it is only possible at the moment to add people as following positions: Support (I think it should be spelled Supporter like Editor and Developer), Editor and Developer. But sometimes an other user is continuing a plugin because for example you don't have the time for it anymore or you create a new organization, which is continuing the plugin as a team. Then it would be vety nice if you can move the plugin with all it's stats to an other organisation or account... If this is going to be implemented it would be nice, if the url would be independent from the username, for example (/resources)/%ID%/pluginName instead of /%USERNAME%/pluginName or at least a redirect to the new location until there is a new project at the exact same name at the exact username similar to GitHub...

This is only an prototype of an idea. Feel free to comment with suggestions for changes or thoughts about this feature request. For further questions you can comment here or mention me on Discord (jo#1081).

**Comment by Machine-Maker** [comment] 2022-06-19 22:31
Duplicate of https://github.com/HangarMC/Hangar/issues/134

**Closed by Machine-Maker** 2022-06-19 22:31 UTC
