### ISSUE TITLE
Browser back pulldown removes query params under certain circumstances

### ISSUE THREAD

**Issue by SlimeDog** [HangarMC/Hangar#1082] opened 2023-01-30 01:54 UTC
### Observed/problematic behavior

Sort order of projects on profile page reverts to `Recently updated` if a project setting changes

### Expected behavior

Selected sort order should be retained

### Steps to reproduce

Chrome 109.0.5414.119 (Official Build) (x86_64) on MacOS 12.6.2 Monterey
- Start on profile page with sort order of projects set to `Name` via slug (i.e., https://hangar.papermc.io/userName?page=0&sort=slug)
- Click a project name, to open the project page
- Click `Settings`
- Edit the `Description` field content
- Click `Save changes`
- Return to the profile page (back 2 pages), using browser `<-` pull-down
- Refresh page with `COMMAND-R` or refresh button

Sort order of projects is `Recently updated`

### UPDATE

See subsequent comment https://github.com/HangarMC/Hangar/issues/1082#issuecomment-1420202821 for a simpler reproduction recipe.

**Comment by kennytv** [comment] 2023-01-30 08:10
Can't reproduce

**Comment by SlimeDog** [comment] 2023-01-30 16:14
I can reproduce this easily. As before, Chrome 109.0.5414.119 (Official Build) (x86_64) on MacOS 12.6.2 Monterey.

Prep work
- In a new browser tab, open a profile page with sort order of projects set to Name via slug in the URL
  - In my case, it is https://hangar.papermc.io/SlimeDog?page=0&sort=slug
- Refresh page with `COMMAND-R` or `refresh` button
  - `Sort by` changes to `Recently updated` briefly, then returns to `Name`
  - This can be repeated indefinitely

Issue reproduction
- Navigate to a project page
  - In my case, click on `AggressiveAnimals`
  - Resulting URL is https://hangar.papermc.io/SlimeDog/AggressiveAnimals
- Navigate to `Settings`
  - URL changes to https://hangar.papermc.io/SlimeDog/AggressiveAnimals/settings
  - The `Description` field contains `Those cute little animals can kill you!`
- Edit the `Description` field content (actually, no changes are required, but it's easier to track)
  - In my case, add an extra exclamation point
  - So the `Description` field contains `Those cute little animals can kill you!!`
  - No other changes
- `Save changes`
- Navigate back two pages, using the `<-` back button in the menubar
  - At first stop, URL is https://hangar.papermc.io/SlimeDog/AggressiveAnimals#general not https://hangar.papermc.io/SlimeDog/AggressiveAnimals
  - At second stop, URL is https://hangar.papermc.io/SlimeDog# not https://hangar.papermc.io/SlimeDog?page=0&sort=slug
- Refresh page with `COMMAND-R` or `refresh` button
  - `Sort by` changes to `Recently updated` and remains there

Unfortunately, this happens intermittently. The URL at the second back-stop is the issue. I repeated this scenario twice more this morning. I have attempted to replicate twice more, without success.

**Comment by SlimeDog** [comment] 2023-02-05 19:17
I have experienced this issue again, following the prod update this morning. Five times in a row.

**Comment by SlimeDog** [comment] 2023-02-07 05:00
Simpler recipe:
- In a new browser tab, open a profile page with sort order of projects set to Name via slug in the URL
  - In my case, it is https://hangar.papermc.io/SlimeDog?page=0&sort=slug
- Refresh page with `COMMAND-R` or `refresh` button
  - `Sort by` changes to `Recently updated` briefly, then returns to `Name`
  - This can be repeated indefinitely
- Navigate to a project page
  - In my case, click on `AggressiveAnimals`
  - Resulting URL is https://hangar.papermc.io/SlimeDog/AggressiveAnimals
- Navigate to Settings
  - URL changes to https://hangar.papermc.io/SlimeDog/AggressiveAnimals/settings
- Navigate back two pages, using the `<-` back pull-down in the menubar 
  - URL is https://hangar.papermc.io/SlimeDog#
  - URL should be https://hangar.papermc.io/SlimeDog?page=0&sort=slug

**Comment by olijeffers0n** [comment] 2023-02-07 18:37
Can replicate these

**Comment by SlimeDog** [comment] 2023-02-08 06:01
I don't think that navigation through the `<- back` pulldown history generally returns
URL = _{base_url}**#**_
instead of
URL = _{base_url}**?**{original_parameters}_
It doesn't happen on other sites I tested. It doesn't seem right.

**Comment by MiniDigger** [comment] 2023-02-11 13:44
> Sort by changes to Recently updated briefly, then returns to Name

that I fixed now, doubt that is related to anything else.

**Comment by MiniDigger** [comment] 2023-02-11 13:56
the other thing is just an issue with how the tab thing for the settings page is implemented, doesn't happen on any other page, not worth wasting time on.

**Closed by MiniDigger** 2023-02-11 13:56 UTC
Labels: 1. bug, 2. frontend
