### ISSUE TITLE
Unable to transfer ownership to an organization.

### ISSUE THREAD

**Issue by RezzedUp** [HangarMC/Hangar#1161] opened 2023-04-22 22:42 UTC
### Observed/problematic behavior

I submitted a plugin using my own account and now I'd like to transfer it to an organization that I created afterwards. I was able to select the organization in the transfer box on the management page, but it indicates that the organization is "pending invite as owner". There doesn't seem to be a way for the organization to accept the invite.

### Expected behavior

There needs to be a way for organizations to accept invites. However, since I own both the organization and the plugin, perhaps the invite could be instantly accepted.

### Steps to reproduce

- Create a new project under a regular user account.
- Attempt to transfer ownership to an organization.
- Get stuck with "pending invite as owner".

**Comment by MiniDigger** [comment] 2023-04-22 22:44
duplicate of https://github.com/HangarMC/Hangar/issues/134
this option should have been disabled because its not implemented yet, but the code that should have disabled it didnt work, I fixed that here https://github.com/HangarMC/Hangar/commit/5d4a526a9284478350364d0a6451f53fdfa60a80

**Closed by MiniDigger** 2023-04-22 22:44 UTC

**Comment by Thorinwasher** [comment] 2025-04-24 10:31
> duplicate of [#134](https://github.com/HangarMC/Hangar/issues/134) this option should have been disabled because its not implemented yet, but the code that should have disabled it didnt work, I fixed that here [5d4a526](https://github.com/HangarMC/Hangar/commit/5d4a526a9284478350364d0a6451f53fdfa60a80)

I tried tranfering ownership from an user to an organization and it did not show any unimplemented operation message, nor were I able to accept the transfer notice in the organization. 

The same thing applies to when I try to add admin permissions to the organization.
