### ISSUE TITLE
Profile website url automatically appends https:// without the user knowing

### ISSUE THREAD

**Issue by FlorianMichael** [HangarMC/Hangar#1382] opened 2024-07-16 03:35 UTC
### Observed/problematic behavior

Putting your website url in your Hangar profile settings like this:
<img width="376" alt="image" src="https://github.com/user-attachments/assets/34427329-ea8e-4ca2-b41e-20d5210ea2c6">
will end up in https://https//florianmichael.de because Hangar automatically puts `https://` at the url start.

### Expected behavior

Detect if the user inputs a website url starting with `https://` and cut it off so the url doesn't end up being wrong.

### Steps to reproduce

1. Open https://hangar.papermc.io/auth/settings/profile or go to your profile settings manually.
2. Add a link with type `Website`
3. Use `https://florianmichael.de` or any other url starting with `https://`
4. Save

### Other
I also just realized that kenny made the same assumption as me: https://hangar.papermc.io/kennytv

_No response_

**Comment by MiniDigger** [comment] 2024-07-16 16:56
duplicate of #1370, prod was just deployed with the fix

**Closed by MiniDigger** 2024-07-16 16:56 UTC
