### ISSUE TITLE
Add ability to delete account (or at least request it)

### ISSUE THREAD

**Issue by Phoenix616** [HangarMC/Hangar#1044] opened 2022-12-23 23:24 UTC
### Is your feature request related to a problem?

Nometimes you just want to not leave stuff lingering around so being able to delete an account (or at least a clear way to request deletion) would be nice. (Deletion requests might be required by EU law anyways)

### Describe the solution you'd like.

A delete or request deletion button in the account settings.

### Describe alternatives you've considered.

Bothering site stuff personally

**Comment by MiniDigger** [comment] 2022-12-23 23:25
Dupe of https://github.com/HangarMC/HangarAuth/issues/173

**Closed by MiniDigger** 2022-12-23 23:25 UTC
