### ISSUE TITLE
Profile-Website-URL invalid

### ISSUE THREAD

**Issue by NonSwag** [HangarMC/Hangar#1381] opened 2024-07-15 19:45 UTC
### Observed/problematic behavior

When clicking on a website listed in a user's profile, it takes you to an invalid page: https://https//... or https://http//...
example profile: https://hangar.papermc.io/kennytv

![image](https://github.com/user-attachments/assets/a97644ea-0bd7-4f75-8818-ebe34e27d8fe)

![image](https://github.com/user-attachments/assets/8450b6e0-efa2-4135-a0f0-5daf4833d3bc)

![image](https://github.com/user-attachments/assets/0139bf6e-ac89-4f37-af0f-2beb4748d706)

### Expected behavior

Should refer to https://kennytv.eu/

### Steps to reproduce

1. add a website to your profile
2. visit your profile main page
3. click on the website

### Other

You are forced to enter a valid URL instead of a domain, therefor it is not a misconfiguration
![image](https://github.com/user-attachments/assets/67e363cb-128f-42e7-9549-ab64075fa939)

**Comment by MiniDigger** [comment] 2024-07-15 20:51
Duplicate of #1370, just needs a deployment

**Closed by MiniDigger** 2024-07-15 20:51 UTC
